### ISSUE TITLE
Hello, brother. How to update the view using gojs in Vue. When the requested data is re rendered, an error is reported: invalid div ID; div already has a diagram associated with it. I am looking forward to your reply. Thank you

### ISSUE THREAD

**Issue by wpc124** [litemerafrukt/katas#13]

**Comment by litemerafrukt** [comment]
Hi!

I think you are referring to another repo then this one. I have a repo with Vue 3 and gojs, that is just a repo for quick experiments and will probably not be either corrected or updated.

To see other examples with gojs and vue you could have a look at the example on gojs example page: https://gojs.net/latest/samples/vue.html and look at a repo that builds a vue wrapper over gojs: https://github.com/whu-luojian/gojs-vue

Good luck, take care.

Cheers
